import React from 'react';
import { getLesson } from '../curriculum.js';
import { LessonShell } from '../components/LessonShell.jsx';
import { Lead, Objectives, Stage } from '../components/prose.jsx';
import { Pathway, DoNow } from '../components/Pathway.jsx';
import { MathBlock, ProblemSet } from '../components/MathBlock.jsx';
import { Rubric } from '../components/Rubric.jsx';
import { FamilyLens } from '../tools/FamilyLens.jsx';

const lesson = getLesson('3.8');

const pathway = [
  { kind: 'read', t: 'Outsourcing and third party risk management — the third-party lifecycle', src: 'PRA Supervisory Statement SS2/21', href: 'https://www.bankofengland.co.uk/prudential-regulation/publication/2021/march/outsourcing-and-third-party-risk-management-ss', min: 18, tier: 'core', why: 'The due-diligence → contract → monitoring → exit lifecycle, from a supervisor that mandates it.' },
  { kind: 'read', t: 'DORA and the oversight of critical ICT third-party providers', src: 'EU Regulation 2022/2554 (applying from January 2025)', href: 'https://eur-lex.europa.eu/eli/reg/2022/2554/oj', min: 20, tier: 'core', why: 'How regulators now reach past the firm to oversee its critical providers directly.' },
  { kind: 'do', t: 'Map your dependencies and add a third-party risk', src: 'the FamilyLens in this lesson → Artifact A10', tier: 'apply', why: 'Turn the supply-chain map into register rows: single-source flags, time-to-replace, an exit gap.' },
  { kind: 'book', t: 'Enterprise Risk Management — the extended-enterprise and outsourcing material', src: 'James Lam, 2nd ed. (2014)', tier: 'deeper' },
];

const retrieval = [
  { q: 'The defining principle of third-party risk is that…', options: [
    { text: 'you can outsource the activity but not the accountability — the supplier’s failure is still your failure to your customers and regulators.', correct: true },
    { text: 'once an activity is outsourced, the risk transfers entirely to the supplier under the contract.' },
    { text: 'third-party risk is purely a procurement cost issue, not a risk-management one.' }] },
  { q: 'Fourth-party (nth-party) risk is…', options: [
    { text: 'the risk in your supplier’s own suppliers — a dependency you rely on but do not contract with and often cannot see.', correct: true },
    { text: 'the risk that a fourth supplier is added to an already-crowded panel.' },
    { text: 'the same as concentration risk, renamed.' }] },
  { q: 'The third-party lifecycle control that most firms skip — and the one regulators most often find missing — is…', options: [
    { text: 'a credible exit / contingency plan with a viable alternative, so you can actually leave or replace the supplier when it fails.', correct: true },
    { text: 'pre-contract due diligence.' },
    { text: 'signing a service-level agreement.' }] },
];

export default function Lesson38() {
  return (
    <LessonShell lesson={lesson} retrieval={retrieval}>
      <Lead>Meridian’s packaging line stops not because Meridian failed, but because one supplier did — and there is no second source. The single most important sentence in this family is the one that explains why that is still entirely Meridian’s problem: you can outsource the activity, but you cannot outsource the accountability.</Lead>

      <p className="measure">Third-party risk is the risk arising from suppliers, vendors, outsourcers, and the wider <strong>extended enterprise</strong> — every organization you depend on to deliver your own service. The activity may sit on someone else’s balance sheet and someone else’s premises, but when it fails your customers are harmed, your service goes down, and your regulator holds you responsible. That asymmetry is the whole subject: a contract can move the work and even reassign some of the financial loss, but it cannot move the duty you owe to the people who rely on you. The supplier’s outage is your outage. The supplier’s bribe is your fine.</p>

      <p className="measure">Why this family has swelled from a procurement footnote to a board-level concern is a story of four structural shifts. <strong>Outsourcing</strong> moved core activities — IT, payroll, logistics, even compliance functions — outside the firm. <strong>Cloud concentration</strong> means a handful of hyperscale providers now sit beneath most digital services, so a single provider’s region failing takes down thousands of unrelated firms at once. <strong>Just-in-time supply chains</strong> stripped out the inventory buffers that once absorbed a supplier hiccup, so a two-week disruption now becomes a two-week stoppage. And <strong>deep sub-tiers</strong> mean your supplier depends on suppliers you have never heard of, three or four layers down. The dependency grew faster than the discipline to manage it.</p>

      <p className="measure">Work the topic in this order — the PRA outsourcing statement for the third-party lifecycle the discipline is built around, then DORA for how regulators now reach past your firm to oversee your critical providers directly, then the build where you map your own dependencies and turn them into register rows with a single-source flag and an exit gap.</p>

      <Pathway lessonId="3.8" items={pathway} />

      <Objectives items={[
        'State the defining principle — outsource the activity, not the accountability — and explain why outsourcing, cloud concentration, JIT, and deep sub-tiers grew this family.',
        'Distinguish single-source / concentration risk, fourth-party (nth-party) risk, and the systemic concentration that arises when everyone depends on the same few providers.',
        'Apply the four-stage third-party lifecycle: due diligence before, SLAs and right-to-audit in the contract, ongoing monitoring during, and exit / contingency planning with a viable alternative for after.',
        'Map and tier your supply chain, locate the single points of failure and the exit gaps, and add third-party risks to your register (Artifact A10).',
      ]} />

      <Stage n={1} kicker="Understand the discipline" title="Mapping the extended enterprise, then controlling its lifecycle" />
      <p className="measure">You cannot manage what you have not mapped, so the discipline begins with <strong>supply-chain mapping and tiering</strong>. Map means: for each important service you deliver, list the third parties it depends on, then trace those dependencies down — your supplier (tier one), your supplier’s critical suppliers (tier two), and onward. Tier means: rank those relationships by how badly their failure would hurt you, not by how much you spend with them — a tiny vendor holding the only copy of a critical certificate can outrank a large one that is trivially replaceable. The map is what converts a vague unease about “supply-chain risk” into a finite list of named dependencies you can actually do something about.</p>

      <p className="measure">The map immediately surfaces two distinct exposures. <strong>Single-source / concentration risk</strong> is the textbook single point of failure: one supplier, one cloud provider, one chip foundry, with no qualified alternative ready to step in. The danger is not the supplier’s quality — it may be excellent — but the absence of a Plan B, so any interruption becomes total. <strong>Fourth-party (or nth-party) risk</strong> is subtler: your supplier’s own suppliers, the dependencies you rely on but do not contract with and frequently cannot even see. If your cloud vendor itself depends on a single power utility or a single sub-processor, that hidden dependency is yours too, inherited without a contract to govern it. Mapping past tier one is the only way fourth-party risk stops being invisible.</p>

      <p className="measure">Against those exposures the discipline applies a four-stage <strong>third-party lifecycle</strong>, and the test of a mature programme is that it does all four rather than just the first. <strong>Before</strong> — due diligence: assess the supplier’s financial health, security, controls, and resilience <em>before</em> you commit, proportionate to how critical the relationship will be. <strong>In the contract</strong> — build the controls into the agreement itself: service-level agreements (SLAs) that define the standard and the remedy, a <strong>right-to-audit</strong> clause so you can verify rather than trust, breach-notification duties, and sub-contracting limits that govern the fourth parties. <strong>During</strong> — ongoing monitoring: the supplier that passed due diligence two years ago may be quietly deteriorating now, so track performance, financial-distress signals, and concentration drift continuously, not once at onboarding. <strong>After / when it fails</strong> — exit and contingency planning, backed by a <em>viable alternative</em>: a documented, tested plan to leave or replace the supplier, and a second source or fallback you could actually switch to. This last stage is the one organizations most often skip and supervisors most often find missing — an exit plan that names no real alternative is not a plan, it is a hope.</p>

      <p className="measure">The reason regulators now treat this as their business, not just yours, is the <strong>operational-resilience link</strong>: third parties sit <em>inside</em> your important business services (lesson 3.4), so a third party’s failure is your service outage and your impact-tolerance breach. Because so many firms now lean on the same few providers, that link scales into a <strong>systemic</strong> concern — when everyone depends on the same cloud, logistics, or payments provider, a single provider failing is a shared, correlated outage across the whole market, exactly the hidden common driver that the portfolio view of Part 3 exists to surface.</p>

      <p className="measure">Supervisors have responded by reaching past the firm to the provider: the EU’s <strong>Digital Operational Resilience Act (DORA)</strong>, applying to financial entities from January 2025, brings <em>critical ICT third-party providers</em> under direct oversight, and the UK’s <strong>critical third parties regime</strong> (HM Treasury / Bank of England / FCA, with the regulators’ rules finalised in 2024) lets supervisors set requirements on designated critical providers directly. The accountability still cannot be outsourced — but now the supplier is watched too.</p>

      <p className="measure">Watch this land on Meridian, where the family wears two very different faces. <strong>R1</strong> is the textbook single point of failure: one supplier provides a critical packaging resin with <em>no qualified second source</em>, an 8%-per-year, ~€9m exposure. Map it and the gap is stark — the important business service is “supply finished product to key retailers,” the sole dependency is this one resin supplier, and there is no viable alternative, so if it fails the line halts and Meridian cannot ship for roughly two weeks. The lifecycle diagnosis writes itself: due diligence and an SLA may exist, but the <em>after</em> stage is empty, which is precisely why qualifying a second resin source becomes the priority treatment — the missing viable alternative is the whole finding. <strong>R8</strong> shows the other face: an overseas sales agent pays a bribe in an emerging market, a 7%-per-year, ~€8m fine-and-ban exposure. The agent is a third party, and the bribe is third-party <em>conduct</em> risk — a misconduct you did not commit but remain fully liable for under anti-bribery law, because you cannot outsource the accountability for how your agents behave in your name. Here the lifecycle controls are anti-corruption due diligence before appointment, contractual compliance and audit rights, and ongoing conduct monitoring. Sitting behind both is the <strong>ERP / cloud dependency</strong> (R2): the group’s core systems run on outsourced cloud hosting, so the cloud provider is a tier-one third party whose region outage is Meridian’s order-and-dispatch outage — a fourth-party question lurks beneath it (what does that provider itself single-source?). Three relationships, one principle: the activity is theirs, the accountability is Meridian’s.</p>

      <DoNow>Before the build, skim the PRA SS2/21 sections on the third-party lifecycle and exit planning (pathway step 1, ~18 min) — you will map one of your own dependencies through those same four stages in the FamilyLens.</DoNow>

      <Stage n={2} kicker="Quantify — what the maths does" title="Mostly scenario, honestly — ‘what if this supplier fails?’" />
      <p className="measure">Be honest about the quantification here: third-party risk is sized far more by <strong>scenario</strong> than by formula, because the events that matter are rare, idiosyncratic to one relationship, and poorly served by historical loss data — you have usually not seen your sole supplier fail, which is exactly the problem. So the primary tool is the disruption scenario: <em>what if this supplier failed tomorrow?</em> You answer it with three concrete, estimable quantities. <strong>Single-source dependency</strong>: is there a qualified alternative, yes or no — a binary flag that often matters more than any probability. <strong>Time-to-replace</strong>: how long, realistically, to stand up an alternative — days for a commodity input, many months for a qualified resin supplier or a migrated core system — because that duration, set against your impact tolerance, tells you whether the dependency is survivable. <strong>Concentration across the vendor base</strong>: how much of your spend, your critical services, or your data sits with one provider, or with several providers that secretly share a fourth party. These three turn a worry into a sized exposure without pretending to a precision the data cannot support.</p>

      <p className="measure">Where a number is wanted, the honest move is to borrow the operational-risk frame: a likelihood the supplier fails in a year and a severity equal to the disruption cost over the time-to-replace — Meridian’s R1 at 8% and ~€9m is exactly this, a frequency × severity estimate where the severity is driven by the two-week stoppage. But the decision usually turns on the scenario and the flags, not the expected loss: a 2%-probability sole-source failure with a six-month time-to-replace and no alternative can be far more threatening than a 20%-probability event you can route around in a day. The systemic angle resists single-firm numbers entirely — when the loss is correlated across the whole market, your standalone estimate understates it, which is why concentration is surfaced as a <em>flag</em> for the portfolio view rather than added up as if independent.</p>

      <MathBlock>
        <p>The decision rule is a comparison, not a distribution. For a critical dependency, the question is whether you can survive its loss within your tolerance:</p>
        <p style={{ textAlign: 'center' }}><span className="eq">time-to-replace ≤ impact tolerance</span> &nbsp;?</p>
        <p>If the realistic time to stand up an alternative exceeds the maximum disruption the service can tolerate (lesson 3.4), the dependency is a failure under test <em>regardless of how unlikely</em> the supplier is to fail — and the treatment is to shorten time-to-replace (qualify a second source, hold a buffer, build an exit plan), not to recompute the probability. Where a loss number is needed, the operational-risk form applies — annual exposure <span className="eq">≈ P(supplier fails) · (disruption cost over time-to-replace)</span> — but for concentration the standalone number understates the danger, because a shared provider failing hits many exposures at once: that correlation is flagged for aggregation, not summed as if independent.</p>
      </MathBlock>

      <Stage n={3} kicker="Build it — your organization" title="Map your dependencies and find the gap" />
      <p className="measure">Now do for your own organization what the map did for Meridian’s R1. Walk your important services and, for each, name the third parties it depends on; for at least one critical dependency, push past tier one and ask what your supplier itself single-sources (the fourth-party question). Write each as a cause → event → consequence, and for the most critical one, record the three sizing facts from Stage 2 — single-source flag (is there a qualified alternative?), time-to-replace, and where this relationship sits in your concentration picture. Then run it through the lifecycle and find the stage that is empty: most often it is the <em>after</em> — an exit plan with a viable alternative.</p>

      <FamilyLens lessonId="3.8" artifactId="A10-thirdparty" family="Third-party" ownerHint="procurement / COO"
        sizing="single-source dependency, time-to-replace, and concentration across the vendor base — largely scenario-based ('what if this supplier fails?')" />

      <p className="measure">Read each entry back through the question that separates a managed dependency from a blind one: <em>if this supplier went dark tomorrow, do I have a named alternative and a time-to-replace inside my tolerance — or am I just trusting that it won’t?</em> Note where each risk sits in the lifecycle, because that is where the work is: a relationship with strong due diligence and a strong SLA but no exit plan is still a single point of failure. The standard to hold your entries to:</p>

      <Rubric
        title="a strong third-party risk entry"
        criteria={[
          { c: 'Accountability located, not transferred', good: 'the entry treats the supplier’s failure as the firm’s failure to its customers and regulator — not as risk the contract has shipped away' },
          { c: 'Mapped to an important business service', good: 'names the service the dependency sits inside, and pushes at least one critical relationship past tier one to the fourth party' },
          { c: 'Single-source flag and time-to-replace', good: 'states whether a qualified alternative exists and how long it would realistically take to switch — the facts the decision turns on' },
          { c: 'Lifecycle stage identified', good: 'locates which of due-diligence / contract / monitoring / exit is missing — usually a credible exit plan with a viable alternative' },
          { c: 'Concentration surfaced for the portfolio', good: 'flags where one provider (or a shared fourth party) sits behind several services, so it feeds aggregation rather than hiding in a silo' },
        ]}
        exemplar="Meridian R1: sole-source resin supplier (8%/yr, ~€9m) inside service ‘supply key retailers’ → single-source flag YES, no qualified alternative, time-to-replace ≫ tolerance → exit stage empty → treatment: qualify a second source. R8: overseas agent’s bribe (7%/yr, ~€8m) → third-party CONDUCT risk, accountability retained → anti-bribery due diligence + audit rights + monitoring."
      />

      <ProblemSet items={[
        { q: 'A procurement lead says “we’ve outsourced our entire IT to one excellent cloud provider with a watertight contract and a strong SLA, so that risk is handled.” Identify the two errors in that sentence.', solution: 'First, the contract has not handled the *accountability*: an SLA defines a remedy (a service credit, a penalty) but it does not keep your service running — when the provider’s region fails, your customers are still down and your regulator still holds you responsible. A penalty is compensation, not resilience. Second, “one provider” is the risk, not the reassurance: a single-source dependency with no viable alternative means any outage is total, and the provider’s quality is irrelevant to that. The missing controls are the *after* stage — a tested exit / contingency plan and a viable fallback (a second region, a portable architecture, or a degraded manual mode) — plus a look past tier one at what that provider itself single-sources (the fourth-party question). “Excellent” and “watertight” describe due diligence and contract; they say nothing about exit.' },
        { q: 'Meridian carries R1 (sole-source resin, 8%/yr, ~€9m) and R8 (an overseas agent’s bribe, 7%/yr, ~€8m). Both are third-party risks — why do they need completely different treatments, and what is the one principle they share?', solution: 'They share the defining principle: in both, Meridian outsourced the activity but kept the accountability — the supplier’s failure (a halted line) and the agent’s misconduct (a bribe) are each fully Meridian’s liability. But the failure modes differ, so the controls differ. R1 is a *continuity / single-source* risk: the treatment is to shorten time-to-replace — qualify a second resin source, hold an inventory buffer, build an exit plan — because the danger is the absence of an alternative, not bad behaviour. R8 is third-party *conduct* risk: the treatment is anti-bribery due diligence before appointment, contractual compliance and audit rights, and ongoing conduct monitoring, because the danger is what the agent does in Meridian’s name, not whether the agent disappears. One is “can we keep operating if they fail?”; the other is “are they behaving lawfully on our behalf?” — and the accountability is non-transferable in both.' },
      ]} />

      <p className="measure">Third-party risk taught you that the boundary of your organization is not the boundary of your risk: the extended enterprise extends your accountability with it, down through sub-tiers you may never have mapped and across providers the whole market shares. That shared dependency is the bridge to the part’s capstone — the same cloud vendor behind your operational, technology, and conduct exposures is exactly the hidden common driver the portfolio view exists to expose, and a concentration that no single silo report would ever surface. Next, the family that turns the organization’s own models into a source of risk.</p>
    </LessonShell>
  );
}
