import React from 'react';
import { getLesson } from '../curriculum.js';
import { LessonShell } from '../components/LessonShell.jsx';
import { Lead, Objectives, Stage } from '../components/prose.jsx';
import { Pathway, DoNow } from '../components/Pathway.jsx';
import { MathBlock, ProblemSet } from '../components/MathBlock.jsx';
import { Rubric } from '../components/Rubric.jsx';
import { FamilyLens } from '../tools/FamilyLens.jsx';

const lesson = getLesson('3.9');

const pathway = [
  { kind: 'read', t: 'IFRS S1 — General Sustainability-related Disclosures', src: 'IFRS Foundation / ISSB', href: 'https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s1-general-requirements/', min: 14, tier: 'core', why: 'The financial-materiality baseline: what a firm must disclose about sustainability risks that affect its own value.' },
  { kind: 'read', t: 'ESRS & double materiality — the CSRD standards', src: 'EFRAG (EU)', href: 'https://www.efrag.org/en/sustainability-reporting', min: 16, tier: 'core', why: 'Where double materiality is law: impact materiality *and* financial materiality, both required.' },
  { kind: 'read', t: 'Aggregate Confusion: the divergence of ESG ratings', src: 'Berg, Kölbel & Rigobon (MIT, 2022)', href: 'https://academic.oup.com/rof/article/26/6/1315/6590670', min: 18, tier: 'core', why: 'The evidence that ESG ratings from different providers barely agree — and why.' },
  { kind: 'do', t: 'Add ESG & sustainability risks to your register', src: 'the FamilyLens in this lesson → Artifact A10-esg', tier: 'apply', why: 'Run a double-materiality and disclosure-gap pass; place each issue in the family where it actually bites.' },
  { kind: 'book', t: 'Fundamentals of Risk Management — the sustainability chapter', src: 'Hopkin & Thompson', tier: 'deeper' },
];

const retrieval = [
  { q: 'What does "double materiality" mean?', options: [
    { text: 'Two distinct lenses: financial materiality (how an ESG issue affects the firm’s value) and impact materiality (how the firm affects people and the environment) — EU CSRD/ESRS require both; ISSB IFRS S1 focuses on the financial lens.', correct: true },
    { text: 'Reporting every ESG metric twice for assurance.' },
    { text: 'That ESG issues are twice as important as financial ones.' }] },
  { q: 'Why is greenwashing a live risk, and what is "greenhushing"?', options: [
    { text: 'Over-claiming a green record invites regulatory, legal, and reputational blowback when reality falls short; greenhushing is the opposite — staying silent on genuine progress to avoid scrutiny, which forfeits credit and can itself mislead.', correct: true },
    { text: 'Greenwashing is a printing technique; greenhushing is a noise-reduction standard.' },
    { text: 'Both are obsolete since the EU Omnibus removed all ESG rules.' }] },
  { q: 'A board cites a high ESG score from one rating agency as proof its ESG risk is managed. The flaw is…', options: [
    { text: 'ESG ratings diverge sharply across providers — they measure different things with different weights, so one score is an opinion, not an assurance that underlying risks are controlled.', correct: true },
    { text: 'the score should have been from a credit-rating agency instead.' },
    { text: 'nothing — a single ESG score fully proves risk is managed.' }] },
  { q: 'Where do ESG risks mostly get *managed*?', options: [
    { text: 'Through the other risk families — operational, conduct, reputational, strategic — that they express through; ESG is the lens that surfaces them, not a separate silo to run in parallel.', correct: true },
    { text: 'In a standalone ESG department, isolated from the rest of the risk function.' },
    { text: 'Only in the climate scenario model from lesson 3.6.' }] },
];

export default function Lesson39() {
  return (
    <LessonShell lesson={lesson} retrieval={retrieval}>
      <Lead>In 2015 Volkswagen’s emissions-cheating scandal wiped roughly a third off its market value within days — not because of a flood or a hacked server, but because the gap between what it claimed about the environment and what it actually did became public. ESG risk is rarely a new hazard; it is the old families viewed through a lens that catches exposures the silos miss.</Lead>

      <p className="measure">ESG — environmental, social, and governance — is best understood not as a fourth thing alongside risk and return but as a <em>lens</em> that surfaces exposures the traditional families under-weight. <strong>Environment</strong> reaches well beyond carbon: water stress, biodiversity loss, waste and pollution, and resource scarcity (climate itself is the subject of lesson 3.6 — this lesson goes broader and does not repeat it). <strong>Social</strong> covers labour conditions and human rights across the supply chain, health and safety, diversity and inclusion, community impact, and product responsibility. <strong>Governance</strong> covers board effectiveness, business ethics, executive pay, and anti-corruption — overlapping heavily with the governance lesson (1.4) and the conduct/compliance family (3.5). The discipline of this lesson is to look through that lens, find the exposures, and then route each one to the family where it is actually managed.</p>

      <p className="measure">Here is how to work through the topic — IFRS S1 for the financial-materiality baseline, the EU’s ESRS for where double materiality is law, then the ratings-divergence evidence, before you run your own organization through a double-materiality and disclosure-gap pass.</p>

      <Pathway lessonId="3.9" items={pathway} />

      <Objectives items={[
        'Map what E, S, and G actually cover — environment beyond carbon, social across the supply chain, governance overlapping 1.4 and 3.5 — with climate itself left to 3.6.',
        'Explain double materiality: financial vs impact materiality, and which regimes require which (EU CSRD/ESRS both; ISSB IFRS S1 financial) — as of 2026.',
        'Name greenwashing and greenhushing as live risks, and read ESG ratings as divergent opinions, not assurances.',
        'Treat ESG as both risk and opportunity, and place the current politicisation/backlash neutrally and attributed.',
        'Add ESG & sustainability risks to your own register, routing each to the family where it bites (Artifact A10-esg).',
      ]} />

      <Stage n={1} kicker="Understand the discipline" title="A lens, not a silo" />
      <p className="measure">Start with the single concept that organises the whole field: <strong>double materiality</strong>. Traditional risk asks one question — <em>how does this issue affect the value of the firm?</em> That is <strong>financial materiality</strong> (sometimes "outside-in"): a drought that raises input costs, a labour scandal that loses a contract, a governance failure that triggers a fine. ESG reporting in much of the world adds a second, distinct question — <em>how does the firm affect people and the environment?</em> That is <strong>impact materiality</strong> ("inside-out"): the firm’s emissions, its water draw, the conditions in its supply chain, regardless of whether those ever rebound onto its accounts. The two lenses can diverge: an issue can be hugely impactful to the world yet, for now, financially immaterial to the firm — and vice versa. The regimes split exactly here, and naming the split correctly is part of the competence.</p>

      <p className="measure">As of 2026, the landscape is two-track. The <strong>EU’s CSRD</strong> (Corporate Sustainability Reporting Directive), implemented through the <strong>ESRS</strong> (European Sustainability Reporting Standards, EFRAG), requires <em>both</em> lenses — full double materiality — and has been phasing in from financial year 2024. The <strong>ISSB</strong>’s <strong>IFRS S1</strong> (general sustainability disclosures) and <strong>IFRS S2</strong> (climate, the standard met in 3.6), effective for annual periods from 1 January 2024, deliberately focus on <em>financial</em> materiality — what investors need to price the firm. So the same company can owe an impact-materiality account in the EU and a financial-only account under an ISSB-aligned regime. A live wrinkle: the <strong>EU Omnibus</strong> simplification package (proposed early 2025) has been narrowing CSRD’s scope and timing — fewer firms in-scope, lighter requirements — so the exact obligations are in flux; advise on the current consolidated text, not the 2024 version. (CSRD/ESRS phasing from 2024 with scope changes under the EU Omnibus as of 2025; ISSB S1/S2 from 2024 — attributed by source and year.)</p>

      <p className="measure">Three more ideas you need before building. First, <strong>greenwashing</strong> is a live risk in its own right: over-claiming a green record — a "net zero" pledge with no credible plan, a "sustainable" label the product cannot support — invites regulatory action, litigation, and reputational blowback the moment the gap is exposed (the Volkswagen case in the lead is the archetype). Its mirror image is <strong>greenhushing</strong>: deliberately staying quiet about genuine sustainability progress to avoid scrutiny or backlash — which forfeits the credit, can itself mislead, and increasingly draws its own regulatory attention. Second, <strong>ESG ratings</strong> are widely used and widely inconsistent: research (notably Berg, Kölbel & Rigobon, MIT 2022) finds scores from different providers correlate only weakly, because they measure different attributes, weight them differently, and even disagree on what counts — so a single ESG score is an <em>opinion</em>, not an assurance that the underlying risks are controlled. Third, ESG is <strong>risk and opportunity</strong>: the same transition that threatens a high-carbon product line opens a premium, lower-impact one — the lens points both ways.</p>

      <p className="measure">Finally, place the politicisation neutrally and attributed, because a board will ask. As of 2025–26 ESG has become contested: parts of the US have seen organised <em>anti-ESG</em> sentiment — state laws restricting ESG considerations in public investment, and asset managers retreating from climate coalitions — while in Europe the <em>EU Omnibus</em> simplification cuts the other way, easing the reporting burden many firms found heavy. The point for a risk manager is not to take a side. It is that the <em>regulatory and reputational environment around ESG is itself a source of uncertainty</em> — the rules, labels, and expectations are moving — which is exactly why ESG belongs on the register as something to monitor, not as a settled compliance checklist.</p>

      <p className="measure"><strong>Meridian worked example.</strong> The ESG lens surfaces three exposures, and the discipline is to route each to where it is managed. <strong>R13 — packaging and carbon regulation plus the retailer’s 18-month decarbonisation ultimatum</strong> (45% annual probability, ~€6.0m, owned by the Sustainability Lead): this is the transition risk taught in 3.6, but the ESG lens sharpens its <em>commercial</em> edge — a key retailer (part of the 18%-of-revenue top customer) has put Meridian on notice that it must publish a credible decarbonisation plan within <em>18 months</em> to keep premium shelf space, so the risk lives jointly in <em>transition</em>, <em>strategic</em>, and <em>commercial</em>. <strong>Supply-chain labour and human-rights exposure</strong> (the Social "S"): Meridian sources agricultural commodities through extended chains, and a forced-labour or unsafe-conditions finding at a supplier would be a conduct, reputational, and operational hit — which is why it is managed inside the third-party programme of lesson 3.8, with ESG as the lens that flagged it. <strong>A greenwashing risk</strong>: if Meridian’s marketing claims a sustainability record its actual footprint cannot support, it courts regulatory and reputational damage — managed as a conduct risk (3.5), surfaced here. Notice none of these is a brand-new hazard; ESG named them and sent each home.</p>

      <DoNow>Before the build, skim the ESRS double-materiality material (pathway step 2, ~16 min) and pick one issue your organization faces that is impactful to the world but not yet financially material to you — and one that is the reverse. You will sort exactly these in a moment.</DoNow>

      <Stage n={2} kicker="Quantify — what the maths does" title="Mostly qualitative, with emerging metrics" />
      <p className="measure">ESG is the family where the honest answer is that most of it does not yet reduce to a clean distribution, and pretending otherwise is its own risk. The core analytical move is not a calculation but a <strong>double-materiality assessment</strong>: take each ESG issue and place it on two axes — financial materiality (how much firm value rides on it) and impact materiality (how much the firm affects the world through it). The output is a 2×2 map that tells you which issues to disclose under which regime and which to escalate as risk. It is structured judgment, not a model; its value is that it forces the two questions to be asked separately rather than collapsed into a single vague "ESG score."</p>

      <p className="measure">The companion move is a <strong>disclosure-gap analysis</strong>: line up what each applicable regime requires (ESRS data points if EU CSRD bites; IFRS S1/S2 if an ISSB-aligned regime applies) against what the firm can actually evidence today, and the gaps <em>are</em> the risk register entries — each one a potential greenwashing exposure (a claim you cannot support) or a compliance exposure (a disclosure you cannot produce). Where ESG does meet numbers, the metrics are <em>emerging</em> and partial: greenhouse-gas emissions (Scopes 1, 2, and the notoriously hard 3), water and waste volumes, supply-chain audit coverage, safety-incident rates, board-diversity ratios, and ESG ratings themselves — useful as trend indicators and KRIs, treacherous as point estimates, and (in the case of ratings) divergent across providers. Read them as a dashboard of leading indicators feeding the other families, not as a VaR.</p>

      <p className="measure">For the one ESG channel that genuinely sizes — climate <em>transition</em> — the method is the scenario analysis you already met in 3.6: stress the business against NGFS-style futures and read how value moves, rather than forecasting one number. So the quantitative posture of this family is layered: scenario analysis for transition, emerging metrics as KRIs for the rest, and a double-materiality map plus disclosure-gap analysis as the qualitative backbone that decides what even goes on the register.</p>

      <MathBlock>
        <p>Double materiality is a two-axis screen, not an equation. Place each ESG issue <span className="eq">x</span> by a pair:</p>
        <p style={{ textAlign: 'center' }}><span className="eq">M(x) = ( fin(x), imp(x) )</span>,&nbsp; <span className="eq">fin</span> = effect on firm value,&nbsp; <span className="eq">imp</span> = effect on people/planet.</p>
        <p>An issue enters the risk register when <span className="eq">fin(x)</span> is material; it enters the EU CSRD/ESRS disclosure when <em>either</em> <span className="eq">fin(x)</span> <em>or</em> <span className="eq">imp(x)</span> is material; an ISSB IFRS S1 disclosure turns only on <span className="eq">fin(x)</span>. The disclosure gap for any regime is <span className="eq">required − evidenced</span> across its data points — and each non-empty gap is a greenwashing-or-compliance risk line. Only one sub-channel (climate transition) carries a distribution, and it borrows 3.6’s scenario method: impact <em>per NGFS scenario</em>, a spread, never a point.</p>
      </MathBlock>

      <Stage n={3} kicker="Build it — your organization" title="Add your ESG & sustainability risks" />
      <p className="measure">Now run your organization through the ESG lens. Take each issue in turn — environmental beyond carbon (water, biodiversity, waste, resource scarcity), social (labour and human rights across your supply chain, health and safety, DEI, community, product responsibility), governance (board, ethics, pay, anti-corruption) — and do two passes. First, a <strong>double-materiality screen</strong>: is it financially material, impact-material, or both, and therefore disclosable under which regime? Second, a <strong>disclosure-gap pass</strong>: what does the applicable regime require that you cannot yet evidence? Then — the crucial step — route each surfaced exposure to the family where it is actually managed (operational, conduct, reputational, strategic, or the transition channel of 3.6), with ESG noted as the lens that found it. The FamilyLens below captures the entries; sustainability lead or board owns the lens.</p>

      <FamilyLens lessonId="3.9" artifactId="A10-esg" family="Climate & ESG" ownerHint="sustainability lead / board"
        sizing="double-materiality + disclosure-gap analysis; scenario for transition; mostly qualitative with emerging metrics (emissions, ratings, incidents)" />

      <p className="measure">Read your entries back through the test that separates a real ESG risk line from a virtue statement: <em>does each one name where it is managed and how it would be sized or monitored, or does it just assert "ESG"?</em> An entry with no home family is a slogan; a metric with no method behind it (a bare ESG score, an unevidenced "net zero" claim) is a greenwashing exposure in waiting. The standard to hold the family to:</p>

      <Rubric
        title="a strong ESG & sustainability register entry"
        criteria={[
          { c: 'Surfaced by the right lens', good: 'environment beyond carbon, social across the supply chain, governance — with climate itself handled in 3.6, not duplicated' },
          { c: 'Double materiality applied', good: 'financial and impact materiality assessed separately, with the disclosure regime (EU CSRD/ESRS — both; ISSB IFRS S1 — financial) named for 2026' },
          { c: 'Routed to a managing family', good: 'each exposure sent to operational, conduct, reputational, strategic, or 3.6 transition — ESG noted as the lens, not run as a parallel silo' },
          { c: 'Greenwashing guarded', good: 'every external claim is evidenced; gaps between claim and footprint logged as risk; greenhushing weighed against over-claiming' },
          { c: 'Sized by a fitting method', good: 'transition via NGFS-style scenarios; the rest via emerging metrics as KRIs (emissions, ratings read as divergent opinions, incident rates), not a false point estimate' },
        ]}
        exemplar="Meridian R13 (packaging/carbon + 18-month retailer ultimatum): financially + impact material → ESRS double-materiality, sized across NGFS scenarios, routed to transition + strategic/commercial. Supply-chain labour (S): impact-material now, financially material if exposed → routed to third-party (3.8) + conduct. Marketing-vs-footprint gap → logged as a greenwashing/conduct (3.5) risk."
      />

      <p className="measure">A worked correction, because this is the family’s signature mistake. A team writes: "ESG risk — managed (ESG score: A)." It names no issue, no materiality lens, no managing family, and leans on a single rating that another provider might score a C. Apply the discipline: pick the concrete issue (forced-labour exposure in the agricultural supply chain), run double materiality (impact-material today; financially material the moment a buyer or regulator acts), check disclosure (does ESRS require a value-chain due-diligence statement you cannot yet evidence? — a gap, hence a risk), then route it to where it is managed (the third-party programme of 3.8 plus conduct of 3.5) and size it via supplier-audit coverage as a KRI. Now there is an owner, a method, and a monitored gap — not a letter grade standing in for control. That move, from a one-letter score to a sized, routed, monitored exposure, is what replaces a letter grade with actual control.</p>

      <ProblemSet items={[
        { q: 'A European-listed firm reports a high greenhouse-gas figure that is hugely impactful to the environment but, with no carbon price yet biting its products, not currently material to its earnings. Under double materiality, must it disclose this, and under which regime?', solution: 'Yes — under the EU CSRD/ESRS, which require *both* lenses: the figure is impact-material (large effect on the environment), so it is disclosable regardless of present financial materiality. Under an ISSB IFRS S1-aligned regime, which turns on financial materiality alone, the same figure might not yet require disclosure. The divergence is the whole point of double materiality: an issue can clear the impact threshold while failing the financial one. As of 2026 the firm must also track the EU Omnibus, which is narrowing CSRD scope and timing.' },
        { q: 'Meridian’s marketing wants to launch a "carbon-neutral packaging" campaign ahead of the actual decarbonisation work behind R13. What is the risk, what is the opposite failure, and what should the risk manager advise?', solution: 'The risk is greenwashing: claiming a green record the footprint cannot yet support invites regulatory action, litigation, and reputational blowback if the gap surfaces — and it sharpens R13 by adding a conduct (3.5) exposure on top of the transition risk. The opposite failure is greenhushing: staying silent on genuine progress to dodge scrutiny, which forfeits commercial credit (the retailer wants to see a credible plan) and can itself mislead. The advice: claim only what is evidenced today, disclose the credible plan and its timeline rather than a finished result, and log any claim-vs-footprint gap as a monitored risk line. ESG is here both opportunity (the shelf space) and risk (the over-claim) at once.' },
        { q: 'A board points to a single agency’s "AA" ESG rating as evidence its ESG risk is well managed, and proposes closing the ESG item on the register. Why is that unsound, and what should replace it?', solution: 'ESG ratings diverge sharply across providers (Berg, Kölbel & Rigobon, MIT 2022): they measure different attributes, weight them differently, and disagree on scope, so one agency’s AA is an opinion another might score far lower — it is not an assurance that underlying exposures are controlled. Closing the item also confuses a rating with a management system. Replace it with the discipline of this lesson: a double-materiality map of the firm’s actual ESG issues, a disclosure-gap analysis against the applicable regime, and each surfaced exposure routed to its managing family with an owner and a monitoring metric. The rating becomes one divergent KRI among several, not the conclusion.' },
      ]} />

      <p className="measure">ESG closes the risk universe not by adding a family but by revealing that the families were never as separate as the register implied: a supply-chain labour failure is operational, conduct, reputational, and strategic at once, and only a lens that crosses silos catches it whole. That is precisely the move Part 3 has been building toward — from siloed lists to a portfolio view — and it is where the next part picks up: aggregating these correlated, cross-cutting exposures into a single picture of the firm, then putting honest numbers on the ones that will carry them.</p>
    </LessonShell>
  );
}
